=== maticifp/DAW-LMISGI-MatildeNavascuez/PRACTICA 4/CIFP_XSD.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="cifp">
    <xs:complexType>
      <xs:sequence minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="alumne" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="professor" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="alumne">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nom"/>
        <xs:element ref="llinatges"/>
        <xs:element ref="data_naixement" minOccurs="0"/>
        <xs:element ref="correu" minOccurs="0"/>
        <xs:element ref="telefon" minOccurs="0"/>
        <xs:element ref="adreça" minOccurs="0"/>
        <xs:element ref="data_matricula"/>
        <xs:element ref="curs"/>
      </xs:sequence>
      <xs:attribute name="id" type="xs:integer" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="professor">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nom"/>
        <xs:element ref="llinatges"/>
        <xs:element ref="data_naixement" minOccurs="0"/>
        <xs:element ref="correu" minOccurs="0"/>
        <xs:element ref="telefon" minOccurs="0"/>
        <xs:element ref="adreça" minOccurs="0"/>
        <xs:element ref="data_incorporació"/>
        <xs:element ref="departament"/>
        <xs:element ref="assignatura" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="id" type="xs:integer" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="curs">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="DAM" minOccurs="0"/>
        <xs:element ref="DAW" minOccurs="0"/>
        <xs:element ref="ASIX" minOccurs="0"/>
        <xs:element ref="SMX" minOccurs="0"/>
        <xs:element ref="SEIA" minOccurs="0"/>
        <xs:element ref="ER" minOccurs="0"/>
        <xs:element ref="AUT" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="departament">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Informàtica" minOccurs="0"/>
        <xs:element ref="Electricitat" minOccurs="0"/>
        <xs:element ref="Automoció" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="nom" type="xs:string"/>
  <xs:element name="llinatges" type="xs:string"/>
  <xs:element name="data_naixement" type="xs:string"/>
  <xs:element name="correu" type="xs:string"/>
  <xs:element name="telefon" type="xs:string"/>
  <xs:element name="adreça" type="xs:string"/>
  <xs:element name="data_matricula" type="xs:string"/>
  <xs:element name="data_incorporació" type="xs:string"/>
  <xs:element name="data_inici" type="xs:string"/>
  <xs:element name="data_final" type="xs:string"/>
  <xs:element name="DAM"><xs:complexType/></xs:element>
  <xs:element name="DAW"><xs:complexType/></xs:element>
  <xs:element name="ASIX"><xs:complexType/></xs:element>
  <xs:element name="SMX"><xs:complexType/></xs:element>
  <xs:element name="SEIA"><xs:complexType/></xs:element>
  <xs:element name="ER"><xs:complexType/></xs:element>
  <xs:element name="AUT"><xs:complexType/></xs:element>
  <xs:element name="Informàtica"><xs:complexType/></xs:element>
  <xs:element name="Electricitat"><xs:complexType/></xs:element>
  <xs:element name="Automoció"><xs:complexType/></xs:element>
  <xs:element name="assignatura">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nom_assignatura"/>
        <xs:element ref="data_inici" minOccurs="0"/>
        <xs:element ref="data_final" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="id_assignatura" type="xs:integer" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="nom_assignatura">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="cicle" type="xs:string" use="required"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== maticifp/DAW-LMISGI-MatildeNavascuez/PRACTICA 4/CIFP_XMLXSD.xml
<?xml version="1.0" encoding="UTF-8"?>
<cifp xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="CIFP_XSD.xsd">
    <alumne id="1">
        <nom>Juan</nom>
        <llinatges>Pérez Ramos</llinatges>
        <data_naixement>2004-12-01</data_naixement>
        <correu>juan.perez@hotmail.com</correu>
        <data_matricula>2023-09-10</data_matricula>
        <curs><DAW/></curs>
    </alumne>
   <alumne id="2">
        <nom>Mario</nom>
        <llinatges>Conde López</llinatges>
        <data_naixement>2006-03-11</data_naixement>
        <telefon>675897294</telefon>
        <data_matricula>2025-09-09</data_matricula>
        <curs><DAW/></curs>
    </alumne>
	<alumne id="3">
        <nom>Maria</nom>
        <llinatges>Conde López</llinatges>
        <data_naixement>2006-03-11</data_naixement>
        <adreça>C/Mar Carib,4, 07610, Palma</adreça>
        <data_matricula>2025-09-09</data_matricula>
        <curs><ASIX/></curs>
    </alumne>
    <professor id="100">
        <nom>Marta</nom>
        <llinatges>García Vidal</llinatges>
        <data_incorporació>2015-02-20</data_incorporació>
        <departament><Informàtica/></departament>    
        <assignatura id_assignatura="501">
            <nom_assignatura cicle="DAW">Desarrollo Aplicaciones Web</nom_assignatura>
            <data_inici>2023-09-15</data_inici>
            </assignatura>
        <assignatura id_assignatura="502">
            <nom_assignatura cicle="ASIX">Seguridad Informática</nom_assignatura>
        </assignatura>
    </professor>
	  <professor id="101">
        <nom>Matilde</nom>
        <llinatges>Navascuez</llinatges>
        <data_incorporació>2025-02-20</data_incorporació>
        <departament><Informàtica/></departament>    
        <assignatura id_assignatura="503">
            <nom_assignatura cicle="DAM">Desarrollo de Aplicaciones Multiplataforma</nom_assignatura>
            <data_inici>2023-09-15</data_inici>
        </assignatura>
    </professor>
</cifp>
