=== maticifp/DAW-LMISGI-MatildeNavascuez/PRACTICA 4/CIFP.dtd
<!ELEMENT cifp (alumne | professor)*>
<!ELEMENT alumne (nom, llinatges, data_naixement?, correu?, telefon?, adreça?, data_matricula, curs)>
<!ATTLIST alumne id CDATA #REQUIRED>
<!ELEMENT professor (nom, llinatges, data_naixement?, correu?, telefon?, adreça?, data_incorporació, departament, assignatura*)>
<!ATTLIST professor id CDATA #REQUIRED>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT llinatges (#PCDATA)>
<!ELEMENT data_naixement (#PCDATA)>
<!ELEMENT correu (#PCDATA)>
<!ELEMENT telefon (#PCDATA)>
<!ELEMENT adreça (#PCDATA)>
<!ELEMENT data_matricula (#PCDATA) >
<!ELEMENT curs (DAM|DAW|ASIX|SMX|SEIA|ER|AUT)> 
<!ELEMENT DAW EMPTY> 
<!ELEMENT DAM EMPTY> 
<!ELEMENT ASIX EMPTY> 
<!ELEMENT SMX EMPTY> 
<!ELEMENT SEIA EMPTY> 
<!ELEMENT ER EMPTY> 
<!ELEMENT AUT EMPTY> 
<!ELEMENT data_incorporació (#PCDATA)>
<!ELEMENT departament (Informàtica | Electricitat | Automoció)>
<!ELEMENT Informàtica EMPTY> 
<!ELEMENT Electricitat EMPTY> 
<!ELEMENT Automoció EMPTY> 
<!ELEMENT assignatura (nom_assignatura, data_inici?, data_final?)>
<!ATTLIST assignatura id_assignatura CDATA #REQUIRED>
<!ELEMENT nom_assignatura (#PCDATA)>
<!ATTLIST nom_assignatura cicle (DAM | DAW | ASIX | SMX | SEIA | ER | AUT) #REQUIRED>
<!ELEMENT data_inici (#PCDATA)>
<!ELEMENT data_final (#PCDATA)>

=== maticifp/DAW-LMISGI-MatildeNavascuez/PRACTICA 4/CIFP_XMLDTD.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cifp SYSTEM "cifp.dtd">
<cifp>
    <alumne id="1">
        <nom>Juan</nom>
        <llinatges>Pérez Ramos</llinatges>
        <data_naixement>2004-12-01</data_naixement>
        <correu>juan.perez@hotmail.com</correu>
        <data_matricula>2023-09-10</data_matricula>
        <curs><DAW/></curs>
    </alumne>
    <professor id="100">
        <nom>Marta</nom>
        <llinatges>García Vidal</llinatges>
        <data_incorporació>2015-02-20</data_incorporació>
        <departament><Informàtica/></departament>    
        <assignatura id_assignatura="501">
            <nom_assignatura cicle="DAW">Desarrollo de Aplicaciones Web</nom_assignatura>
            <data_inici>2023-09-15</data_inici>
            </assignatura>
        <assignatura id_assignatura="502">
            <nom_assignatura cicle="ASIX">Seguridad Informática</nom_assignatura>
        </assignatura>
    </professor>
</cifp>
